# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4397640a9fef50b8a8c4c677790243fa23c6c5e91e331f258d348bab7bb59f222f37c095b1ac44ed1d848840fc76338e9ccaf3fcd5916c57b281ddcb96484386

test:
  secret_key_base: f6bab0e454d7d910fd738d2ae8a698759f6e7c9595029584f06a50982362234de120ba2d87c23e36325c74d2ca66539252432c15e3522921107d22f635bb62f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
